import type { ChecklistSection } from './types';

export const STORAGE_KEY_01 = 'orellanaChecklist';

export const SECTIONS_01: ChecklistSection[] = [
  {
    id: 1,
    title: 'Configuración del Laboratorio de Campo',
    items: [
      { id: 1, title: 'Adecuación del espacio físico', objective: 'Preparar un área limpia, seca y protegida para trabajar con hongos.', description: 'Selecciona un espacio cerrado (cuarto, bodega, carpa) con mínimo ingreso de viento y polvo. Pinta paredes con pintura lavable, sella grietas, instala mallas antiinsectos en ventanas. Define zonas: área sucia (preparación de sustrato), área limpia (inoculación), área de incubación y área de fructificación.', completed: false },
      { id: 2, title: 'Construcción/adquisición de cámara de flujo laminar casera', objective: 'Crear un ambiente estéril para la manipulación de micelio sin contaminación.', description: 'Arma una caja de inoculación (still air box) con acrílico transparente y dos agujeros para los brazos, o una cámara de flujo con filtro HEPA y ventilador. Desinfecta con alcohol 70% antes de cada uso.', completed: false },
      { id: 3, title: 'Adquisición de equipo básico de laboratorio', objective: 'Contar con las herramientas mínimas para trabajar con cultivos de hongos.', description: 'Consigue: mechero Bunsen o lámpara de alcohol, bisturí o cuchillo estéril, pinzas, alcohol 70%, agua oxigenada, guantes de nitrilo, tapabocas, cofia, balanza, termómetro, higrómetro, spray pulverizador, bolsas de polipropileno con filtro o microperforadas.', completed: false },
      { id: 4, title: 'Adquisición de la cepa madre (cultivo en agar)', objective: 'Obtener genética limpia y productiva de Pleurotus ostreatus.', description: 'Compra el cultivo madre (slant o placa de agar) a un proveedor confiable (laboratorio micológico, proveedor de insumos). Verifica que sea Pleurotus ostreatus (u otra especie deseada) de buena productividad. Conserva entre 4-8°C en refrigerador.', completed: false },
      { id: 5, title: 'Preparación de medios de cultivo (PDA/PDA modificado)', objective: 'Tener medio nutritivo para multiplicar la cepa madre.', description: 'Prepara Papa-Dextrosa-Agar (PDA): 200g papa hervida, 20g dextrosa, 15-20g agar por litro de agua. Esteriliza en olla a presión 15 psi por 20 min. Vierte en placas Petri estériles cerca de la llama.', completed: false },
    ],
  },
  {
    id: 2,
    title: 'Producción de Micelio (Semilla)',
    items: [
      { id: 6, title: 'Clonación o transferencia a placa de agar', objective: 'Obtener crecimiento activo de la cepa en medio sólido.', description: 'En la cámara de flujo, flamea el bisturí, toma un pequeño fragmento de micelio de la cepa madre y transfiérelo al centro de una placa de PDA. Incuba a 22-25°C en oscuridad por 7-14 días hasta cubrir la placa.', completed: false },
      { id: 7, title: 'Preparación de grano maestro (master grain)', objective: 'Producir grano inoculado a partir del agar para expandir el cultivo.', description: 'Hierve grano (trigo, sorgo o maíz) 20-30 min hasta que esté hidratado pero no reventado. Escurre bien, llena frascos de vidrio al 2/3, tapa con filtro o aluminio. Esteriliza en olla a presión 15 psi por 90 min. Deja enfriar 24h.', completed: false },
      { id: 8, title: 'Inoculación del grano maestro', objective: 'Transferir el micelio del agar al grano estéril.', description: 'En la cámara de flujo, corta la placa de agar en cuadros pequeños y transfiere 3-4 cuadros a cada frasco de grano. Agita suavemente. Incuba a 22-25°C en oscuridad por 14-21 días hasta colonización total.', completed: false },
      { id: 9, title: 'Producción de semilla (grano G2G)', objective: 'Multiplicar el micelio para tener suficiente semilla para los bloques.', description: 'Usa el grano maestro para inocular nuevos frascos con grano estéril (técnica grano a grano, G2G). Proporción: 10-15% de semilla. Colonización en 10-14 días. Esta será la semilla comercial para inocular sustrato.', completed: false },
      { id: 10, title: 'Control de calidad del micelio', objective: 'Verificar que el micelio esté libre de contaminaciones.', description: 'Inspecciona visualmente: micelio blanco algodonoso es sano; manchas verdes (Trichoderma), negras, rosadas o con mal olor indican contaminación. Descarta los frascos contaminados. El micelio sano debe oler a hongos frescos o fermentado suave.', completed: false },
    ],
  },
  {
    id: 3,
    title: 'Preparación del Sustrato',
    items: [
      { id: 11, title: 'Selección del sustrato', objective: 'Elegir el material base más adecuado según disponibilidad local.', description: 'Opciones comunes: paja de trigo/arroz, aserrín de maderas blandas (no tratadas), bagazo de caña, cáscaras de algodón, marlos de maíz triturados, cartón. La paja de trigo es la más usada por su relación costo-rendimiento.', completed: false },
      { id: 12, title: 'Acondicionamiento y triturado', objective: 'Preparar el sustrato con tamaño y humedad adecuados.', description: 'Tritura o corta el sustrato en trozos de 2-5 cm. Sumerge en agua limpia por 12-18 horas para hidratar. El sustrato debe quedar con humedad del 60-70% (al apretar con la mano, solo deben escurrir 1-2 gotas).', completed: false },
      { id: 13, title: 'Pasteurización del sustrato', objective: 'Eliminar microorganismos competidores sin destruir los beneficiosos.', description: 'Método de pasteurización en caliente: sumerge el sustrato en agua a 65-80°C por 60-90 minutos (usa termómetro). Método alternativo con cal hidratada: sumerge en agua con 2g de cal por litro, 16-24 horas a temperatura ambiente. Enjuaga con agua limpia después.', completed: false },
      { id: 14, title: 'Escurrido y enfriamiento', objective: 'Alcanzar humedad y temperatura óptimas para la inoculación.', description: 'Escurre el sustrato sobre una superficie limpia hasta que no escurra agua al apretarlo. Deja enfriar hasta temperatura ambiente (25-28°C) antes de inocular. Nunca inocules sustrato caliente (mata el micelio).', completed: false },
      { id: 15, title: 'Verificación de parámetros del sustrato', objective: 'Confirmar que el sustrato está listo para inoculación.', description: 'Mide pH (ideal 6-7.5), humedad (60-70%) y temperatura (<28°C). Realiza prueba de apretón: al cerrar el puño, solo deben aparecer 1-2 gotas entre los dedos. Si está muy seco, rehidrata; si muy húmedo, extiende y seca.', completed: false },
    ],
  },
  {
    id: 4,
    title: 'Inoculación del Sustrato',
    items: [
      { id: 16, title: 'Desinfección del área y materiales', objective: 'Reducir al mínimo los riesgos de contaminación durante la inoculación.', description: 'Limpia la superficie de trabajo con alcohol 70%. Desinfecta manos con alcohol, usa guantes, tapabocas y cofia. Trabaja cerca de la llama del mechero o dentro de la cámara de flujo. Desinfecta la bolsa de semilla por fuera.', completed: false },
      { id: 17, title: 'Mezcla de sustrato y semilla', objective: 'Distribuir el micelio uniformemente en el sustrato.', description: 'Tasa de siembra: 10-15% de semilla respecto al peso húmedo del sustrato. Mezcla bien en un recipiente limpio desinfectado. Trabaja rápido para minimizar exposición al aire.', completed: false },
      { id: 18, title: 'Empaque en bolsas de fructificación', objective: 'Preparar los bloques para la fase de incubación.', description: 'Llena bolsas de polipropileno (5-10 kg de sustrato compactado). Compacta bien para eliminar bolsas de aire. Cierra la bolsa con anillo y filtro o haz pequeños orificios laterales cubiertos con cinta microporosa. Etiqueta con fecha y cepa.', completed: false },
      { id: 19, title: 'Registro de trazabilidad del lote', objective: 'Documentar cada bloque para seguimiento y control de calidad.', description: 'Registra en bitácora: fecha de inoculación, cepa utilizada, lote de sustrato, lote de semilla, peso del bloque, operador, proveedor del sustrato. Asigna un código único al bloque (ej: ORE-2026-07-001).', completed: false },
    ],
  },
  {
    id: 5,
    title: 'Incubación (Colonización)',
    items: [
      { id: 20, title: 'Acomodación en sala de incubación', objective: 'Crear condiciones óptimas para el crecimiento del micelio.', description: 'Coloca los bloques en estanterías limpias, separados entre sí para permitir circulación de aire. Evita apilarlos. El área debe estar oscura o con luz muy tenue.', completed: false },
      { id: 21, title: 'Control de temperatura', objective: 'Mantener el rango ideal de crecimiento del micelio.', description: 'Temperatura óptima: 22-26°C. Por encima de 30°C el micelio se estresa y aumenta el riesgo de contaminación. Por debajo de 18°C el crecimiento se ralentiza. Monitorea con termómetro 2 veces al día.', completed: false },
      { id: 22, title: 'Control de humedad ambiental', objective: 'Evitar deshidratación del sustrato durante la colonización.', description: 'Humedad relativa: 70-80%. Si el ambiente es muy seco, pulveriza agua en paredes y piso (no sobre los bloques). Evita exceso de humedad que promueva mohos.', completed: false },
      { id: 23, title: 'Ventilación controlada', objective: 'Renovar el aire sin introducir contaminantes.', description: 'Ventila el área 1-2 veces al día por 10-15 minutos. El micelio necesita oxígeno pero el aire debe estar lo más limpio posible. Instala mallas finas en las ventilaciones.', completed: false },
      { id: 24, title: 'Monitoreo de contaminación', objective: 'Detectar y retirar bloques contaminados temprano.', description: 'Revisa los bloques cada 2-3 días. Retira inmediatamente los que presenten manchas verdes, negras, rosadas, mal olor o licuificación. Aísla los bloques sospechosos. La colonización completa toma 18-25 días.', completed: false },
      { id: 25, title: 'Verificación de colonización total', objective: 'Confirmar que el bloque está listo para fructificar.', description: 'El bloque está listo cuando el sustrato se ve completamente blanco (micelio consolidado) y forma un bloque sólido. El tiempo varía según cepa y condiciones (18-30 días).', completed: false },
    ],
  },
  {
    id: 6,
    title: 'Fructificación',
    items: [
      { id: 26, title: 'Inducción de primordios (choque térmico)', objective: 'Estimular la formación de las primeras setas.', description: 'Para muchas cepas de Pleurotus, bajar la temperatura a 10-18°C por 24-48 horas induce la formación de primordios. También ayuda abrir más los orificios de la bolsa para aumentar intercambio gaseoso.', completed: false },
      { id: 27, title: 'Aumento de luz difusa', objective: 'Señalizar al micelio que es momento de fructificar.', description: 'Expón los bloques a luz natural difusa o luz artificial (LED blanco frío) por 10-12 horas al día. Intensidad baja (100-500 lux). Nunca luz solar directa.', completed: false },
      { id: 28, title: 'Control de humedad en fructificación', objective: 'Mantener ambiente húmedo sin encharcar los primordios.', description: 'Humedad relativa: 85-95%. Pulveriza agua en el ambiente (paredes, piso, techo) 3-5 veces al día. Evita mojar directamente los primordios pequeños (se amarillean y mueren).', completed: false },
      { id: 29, title: 'Ventilación intensiva', objective: 'Evitar acumulación de CO₂ que deforme las setas.', description: 'Ventila el área 3-4 veces al día o instala ventilador con extractor. El CO₂ alto produce tallos largos y sombreros pequeños. Mantén renovación constante de aire fresco.', completed: false },
      { id: 30, title: 'Seguimiento del desarrollo', objective: 'Monitorear el crecimiento de los racimos.', description: 'Los primordios aparecen en 5-10 días. Los racimos crecen rápido (duplican tamaño cada 24h). Registra fecha de aparición de primordios y fecha estimada de cosecha.', completed: false },
    ],
  },
  {
    id: 7,
    title: 'Cosecha',
    items: [
      { id: 31, title: 'Determinación del punto de cosecha', objective: 'Cosechar en el momento óptimo de calidad y peso.', description: 'Cosecha cuando los sombreros estén convexos y los bordes aún ligeramente curvados hacia abajo (antes de que se aplanen y liberen esporas). Normalmente 5-7 días después de la aparición de primordios.', completed: false },
      { id: 32, title: 'Técnica de corte o arranque', objective: 'Retirar el racimo sin dañar el sustrato.', description: 'Toma el racimo completo en la base y gira suavemente hasta desprenderlo, o corta con cuchillo estéril en la base. Evita dejar restos que puedan pudrirse en el bloque.', completed: false },
      { id: 33, title: 'Pesaje y registro de rendimiento', objective: 'Calcular la eficiencia biológica (EB) del cultivo.', description: 'Pesa cada racimo inmediatamente después de cosechado. Registra en la bitácora: peso fresco cosechado, número de racimos, fecha. Calcula EB = (peso fresco setas / peso seco del sustrato) × 100. EB típica: 75-120%.', completed: false },
      { id: 34, title: 'Manejo post-cosecha inmediato', objective: 'Preservar la calidad hasta el empaque.', description: 'Coloca las setas en recipientes limpios y ventilados. No las amontones. Mantén a 4-8°C si no se procesan de inmediato. Evita contacto con agua. Procesa en máximo 4-6 horas después de cosecha.', completed: false },
    ],
  },
  {
    id: 8,
    title: 'Empaque y Almacenamiento',
    items: [
      { id: 35, title: 'Selección y clasificación', objective: 'Separar setas por calidad y tamaño para comercialización.', description: 'Clasifica en categorías: A (sombreros enteros, 8-15 cm, sin daños), B (tamaño irregular, pequeños), C (para deshidratar o procesar). Descarta setas con manchas, agujeros o mal olor.', completed: false },
      { id: 36, title: 'Empaque para venta fresca', objective: 'Presentar el producto de forma atractiva y conservar frescura.', description: 'Usa bandejas de telgopor o cartón con film plástico microperforado, o bolsas de papel kraft. Peso típico: 250g o 500g. Etiqueta con: nombre, peso, fecha de cosecha, lote, datos del productor. Vida útil refrigerada: 7-10 días.', completed: false },
      { id: 37, title: 'Almacenamiento en frío', objective: 'Mantener la calidad hasta la distribución.', description: 'Refrigera a 2-4°C con humedad 85-90%. No congeles a menos que sea para procesamiento posterior. Evita fluctuaciones de temperatura. Rotula con fecha de ingreso (PEPS: primero en entrar, primero en salir).', completed: false },
      { id: 38, title: 'Procesamiento alternativo (opcional)', objective: 'Aprovechar excedentes o setas de categoría C.', description: 'Opciones: deshidratado (a 45-55°C hasta humedad <10%), encurtido, congelado (previa cocción), harina de orellana. Cada proceso requiere su propio protocolo y registro.', completed: false },
    ],
  },
  {
    id: 9,
    title: 'Control de Calidad y Trazabilidad',
    items: [
      { id: 39, title: 'Bitácora de producción por lote', objective: 'Documentar todo el proceso para trazabilidad completa.', description: 'Cada lote debe tener registro de: origen de la cepa, fecha de cada etapa, operador, insumos usados, parámetros ambientales, incidencias, rendimientos. Guarda las bitácoras mínimo 2 años.', completed: false },
      { id: 40, title: 'Etiquetado con código de lote', objective: 'Permitir rastrear cualquier producto hasta su origen.', description: 'Cada empaque debe llevar código único de lote (ej: ORE-20260706-A01). El código permite identificar: fecha de cosecha, bloque de origen, cepa, sustrato usado.', completed: false },
      { id: 41, title: 'Control de calidad sensorial', objective: 'Verificar características del producto final.', description: 'Evalúa en cada lote: color (blanco-gris uniforme), olor (fresco, a hongos, sin amoniaco ni podrido), textura (firme, elástica), apariencia (sin manchas, insectos, humedad excesiva).', completed: false },
      { id: 42, title: 'Análisis microbiológico periódico', objective: 'Garantizar inocuidad alimentaria.', description: 'Cada cierto tiempo (mensual o trimestral), envía muestras a laboratorio para análisis de coliformes, mohos y levaduras, Salmonella. Especialmente importante si vendes a restaurantes o tiendas.', completed: false },
      { id: 43, title: 'Gestión de no conformidades', objective: 'Documentar y corregir problemas de calidad.', description: 'Si un lote presenta problemas, regístralo, aíslalo y determina la causa raíz (contaminación, mal sustrato, condiciones ambientales). Aplica acciones correctivas y actualiza los procedimientos.', completed: false },
    ],
  },
  {
    id: 10,
    title: 'Limpieza, Desinfección y Segunda Oleada',
    items: [
      { id: 44, title: 'Limpieza entre ciclos', objective: 'Prevenir acumulación de contaminantes y plagas.', description: 'Desinfecta completamente el área de fructificación entre ciclos. Retira todos los residuos de sustrato. Limpia superficies con solución de cloro al 10% o alcohol 70%. Deja secar y ventilar.', completed: false },
      { id: 45, title: 'Manejo de bloques gastados', objective: 'Aprovechar o disponer adecuadamente el sustrato post-cosecha.', description: 'Los bloques pueden producir 2-3 oleadas (cada una con menor rendimiento). Después, el sustrato gastado es excelente abono/compost para huerta o alimento animal. No lo tires a la basura sin tratar.', completed: false },
      { id: 46, title: 'Estimulación de segunda oleada', objective: 'Aprovechar el bloque para más cosechas.', description: 'Después de la primera cosecha, sumerge el bloque en agua limpia por 12-24 horas, escurre y vuelve a las condiciones de fructificación. La segunda oleada produce 30-50% de la primera.', completed: false },
      { id: 47, title: 'Control de plagas y mosquitos', objective: 'Prevenir infestaciones de mosca del sustrato (Lycoriella).', description: 'Instala trampas amarillas pegajosas, mallas finas en ventanas, revisa bloques con puntos negros (huevos). Mantén higiene extrema. Si hay infestación, retira los bloques afectados y desinfecta.', completed: false },
      { id: 48, title: 'Mantenimiento de equipos', objective: 'Conservar en buen estado las herramientas del laboratorio.', description: 'Esteriliza bisturíes y pinzas después de cada uso. Revisa termómetros e higrómetros. Limpia la cámara de flujo. Revisa el refrigerador. Lleva un registro de mantenimiento.', completed: false },
    ],
  },
  {
    id: 11,
    title: 'Gestión y Registros Generales',
    items: [
      { id: 49, title: 'Planificación de producción', objective: 'Organizar los ciclos para tener cosecha continua.', description: 'Diseña un calendario escalonado: inicia nuevos bloques cada semana para tener cosecha constante. Calcula la demanda del mercado y ajusta la producción.', completed: false },
      { id: 50, title: 'Control de inventarios', objective: 'Llevar registro de insumos y productos.', description: 'Registra entradas y salidas de: sustrato, grano, cepas, bolsas, insumos de limpieza. Controla stock de producto fresco y procesado. Evita quiebres o excesos.', completed: false },
      { id: 51, title: 'Registro financiero básico', objective: 'Conocer costos y rentabilidad del cultivo.', description: 'Anota costos de: insumos, mano de obra, energía, agua, empaque, transporte. Compara con ingresos por venta. Calcula costo por kg producido y margen de ganancia.', completed: false },
      { id: 52, title: 'Capacitación continua', objective: 'Mejorar técnicas y resolver problemas.', description: 'Lee, consulta foros, experimenta con nuevas técnicas. Únete a comunidades de micicultores. Lleva un cuaderno de experimentos y resultados.', completed: false },
      { id: 53, title: 'Cumplimiento normativo', objective: 'Operar dentro del marco legal local.', description: 'Infórmate sobre los requisitos sanitarios para producción y venta de hongos en tu país/región. Si vendes formalmente, podrías necesitar registro sanitario, permisos de funcionamiento, análisis de laboratorio.', completed: false },
    ],
  },
  {
    id: 12,
    title: 'Comercialización',
    items: [
      { id: 54, title: 'Identificación de canales de venta', objective: 'Definir por dónde se venderá el producto para maximizar alcance y rentabilidad.', description: 'Evalúa canales: venta directa en mercado campesino, restaurantes y tiendas naturistas, distribuidores de productos frescos, venta por suscripción (canastas), venta online/redes sociales, ferias agroecológicas. Prioriza según tu contexto y capacidades.', completed: false },
      { id: 55, title: 'Definición del cliente objetivo', objective: 'Conocer a quién le vendes para adaptar producto, precio y comunicación.', description: 'Perfil de clientes potenciales: restaurantes vegetarianos/gourmet, tiendas orgánicas, consumidores conscientes de salud, supermercados locales, hoteles con cocina de autor. Define qué valora cada segmento (frescura, trazabilidad, precio, presentación).', completed: false },
      { id: 56, title: 'Estrategia de precios', objective: 'Fijar precios competitivos que cubran costos y generen margen.', description: 'Calcula el precio mínimo basado en costo de producción + margen deseado. Investiga precios de mercado (orellana fresca suele valer entre 2-4 veces el precio de hongos comunes). Define precios por volumen, descuentos por fidelidad y condiciones de pago.', completed: false },
      { id: 57, title: 'Diseño de presentación y marca', objective: 'Diferenciar el producto en el punto de venta.', description: 'Crea una marca con nombre, logo y línea gráfica coherente. Diseña etiquetas atractivas con: nombre del producto, peso, fecha de cosecha, lote, datos del productor, recomendaciones de uso y almacenamiento. Considera empaques eco-amigables (cartón, papel kraft).', completed: false },
      { id: 58, title: 'Material promocional y muestras', objective: 'Dar a conocer el producto y generar prueba.', description: 'Prepara tarjetas de presentación, fichas técnicas simples, fotos de alta calidad del producto. Ofrece muestras gratuitas a restaurantes y tiendas clave. Elabora un catálogo digital (PDF) con productos disponibles, precios y condiciones.', completed: false },
      { id: 59, title: 'Estrategia digital y redes sociales', objective: 'Aprovechar canales digitales para llegar a más clientes.', description: 'Crea perfiles en Instagram y Facebook con fotos del proceso, recetas, beneficios nutricionales. Publica contenido educativo (cómo cocinar orellana, recetas). Considera WhatsApp Business para pedidos directos.', completed: false },
      { id: 60, title: 'Participación en ferias y mercados', objective: 'Generar visibilidad y contactos comerciales presenciales.', description: 'Identifica ferias agroecológicas, mercados campesinos y eventos gastronómicos en tu región. Prepara stand atractivo con degustaciones. Lleva tarjetas, empaques, y un registro de contactos para seguimiento posterior.', completed: false },
      { id: 61, title: 'Alianzas estratégicas', objective: 'Ampliar el alcance mediante colaboraciones.', description: 'Busca alianzas con: productores de otros hongos o vegetales (para canastas combinadas), chefs que promuevan tu producto, tiendas de productos orgánicos, programas de alimentación saludable de colegios o empresas.', completed: false },
      { id: 62, title: 'Sistema de pedidos y facturación', objective: 'Gestionar ventas de forma ordenada y profesional.', description: 'Implementa un sistema simple (hoja de cálculo, app o software) para registrar pedidos, clientes, fechas de entrega y pagos. Define política de facturación y términos de pago (contado, 8 días, 15 días).', completed: false },
      { id: 63, title: 'Seguimiento post-venta y fidelización', objective: 'Mantener clientes satisfechos y generar recompra.', description: 'Llama o escribe a clientes después de cada compra para conocer su satisfacción. Registra quejas y sugerencias. Ofrece beneficios a clientes recurrentes (descuentos, entregas prioritarias, nuevos productos en primicia).', completed: false },
    ],
  },
  {
    id: 13,
    title: 'Análisis de Costos',
    items: [
      { id: 64, title: 'Identificación de costos fijos', objective: 'Conocer los gastos que se pagan independientemente del nivel de producción.', description: 'Lista todos los costos fijos mensuales: arriendo del espacio, servicios públicos (luz, agua, gas), salarios fijos, seguros, internet, mantenimiento básico, depreciación de equipos. Suma para obtener total de costos fijos mensuales.', completed: false },
      { id: 65, title: 'Identificación de costos variables por bloque', objective: 'Calcular cuánto cuesta producir cada bloque de sustrato inoculado.', description: 'Desglosa por bloque: sustrato (paja/aserrín), cal o insumos de pasteurización, semilla (micelio), bolsa, etiqueta, energía usada en pasteurización, mano de obra directa. Suma para obtener costo variable unitario.', completed: false },
      { id: 66, title: 'Cálculo del costo unitario por kg de orellana', objective: 'Determinar cuánto cuesta producir un kilogramo de seta fresca.', description: 'Fórmula: Costo unitario por kg = (Costos fijos mensuales / kg producidos al mes) + (Costos variables por bloque / kg obtenidos por bloque). Ejemplo: si un bloque de 5 kg de sustrato seco produce 4 kg de setas y el costo variable es $15.000, el costo por kg es $3.750 + proporción de fijos.', completed: false },
      { id: 67, title: 'Análisis de eficiencia biológica (EB)', objective: 'Evaluar qué tan eficiente es tu proceso productivo.', description: 'EB = (peso fresco de setas cosechadas / peso seco del sustrato) × 100. Una EB del 75-100% es buena; superior al 100% es excelente. Compara EB entre lotes, cepas y sustratos para identificar qué combinación es más rentable.', completed: false },
      { id: 68, title: 'Cálculo del punto de equilibrio', objective: 'Saber cuántos kg debes vender al mes para cubrir todos los costos.', description: 'Punto de equilibrio (en kg) = Costos fijos mensuales / (Precio de venta por kg - Costo variable por kg). Ejemplo: si fijos son $500.000, precio de venta $12.000/kg y costo variable $5.000/kg, el punto de equilibrio es 500.000 / 7.000 = 71,4 kg/mes.', completed: false },
      { id: 69, title: 'Proyección de ingresos y flujo de caja', objective: 'Anticipar la salud financiera del negocio.', description: 'Elabora una proyección mensual a 6-12 meses con: producción estimada (bloques × rendimiento), ingresos por ventas, egresos por costos fijos y variables. Calcula flujo de caja mensual. Identifica meses críticos donde puedas necesitar capital de trabajo.', completed: false },
      { id: 70, title: 'Análisis de rentabilidad por producto/canal', objective: 'Identificar qué productos y canales dejan más margen.', description: 'Compara rentabilidad de: venta fresca vs deshidratada, venta directa vs a distribuidor, diferentes presentaciones (250g vs 500g vs a granel). Enfoca esfuerzos en lo más rentable. Considera también el tiempo invertido por canal.', completed: false },
      { id: 71, title: 'Registro contable básico', objective: 'Llevar un control financiero ordenado y trazable.', description: 'Usa una hoja de cálculo o software contable simple (Siigo, Alegra) para registrar: ingresos por venta, costos de insumos, salarios, servicios, otros gastos. Genera un estado de resultados mensual.', completed: false },
      { id: 72, title: 'Evaluación de inversión inicial y retorno', objective: 'Saber en cuánto tiempo se recupera la inversión.', description: 'Suma todos los costos de arranque: adecuación del espacio, equipos, primera compra de insumos, trámites. Calcula ROI = Utilidad anual / Inversión inicial × 100. Periodo de recuperación = Inversión / Utilidad mensual promedio.', completed: false },
      { id: 73, title: 'Optimización continua de costos', objective: 'Mejorar la rentabilidad mes a mes.', description: 'Revisa mensualmente las partidas de mayor gasto. Busca alternativas: negociar con proveedores, comprar sustrato a granel, optimizar consumo energético, reducir mermas por contaminación. Establece metas de reducción de costos trimestrales.', completed: false },
      { id: 74, title: 'Separación de finanzas personales y del negocio', objective: 'Mantener claridad financiera y facilitar la toma de decisiones.', description: 'Abre una cuenta bancaria exclusiva para el negocio. Págate un salario fijo como operador, no retires dinero arbitrariamente de la caja. Reinvierte utilidades según plan de crecimiento.', completed: false },
    ],
  },
  {
    id: 14,
    title: 'Registro Sanitario INVIMA',
    items: [
      { id: 75, title: 'Verificación de requisitos aplicables', objective: 'Confirmar qué permisos necesitas según tu modelo de negocio.', description: 'Si vendes orellana fresca sin procesar a consumidor final, los requisitos son menores. Si procesas (deshidratada, encurtida, harina) o vendes a restaurantes/tiendas formales, probablemente necesites Registro Sanitario INVIMA. Consulta la normativa vigente (Resolución 2659 de 2011 y actualizaciones).', completed: false },
      { id: 76, title: 'Constitución legal de la empresa', objective: 'Formalizar el negocio para poder tramitar permisos sanitarios.', description: 'Constituye la empresa en Cámara de Comercio (SAS es la figura más común). Obtén RUT ante la DIAN. Define en el objeto social la producción y comercialización de hongos comestibles. Este es requisito previo para cualquier trámite INVIMA.', completed: false },
      { id: 77, title: 'Permiso de uso de suelo', objective: 'Contar con el aval del municipio para la actividad en la ubicación.', description: 'Solicita concepto de uso de suelo en la oficina de planeación municipal. Verifica que la zona permita actividad agroindustrial o de transformación de alimentos. Sin este permiso no puedes avanzar con INVIMA.', completed: false },
      { id: 78, title: 'Adecuación de instalaciones según normativa', objective: 'Cumplir con los requisitos físicos que exige el INVIMA.', description: 'Las instalaciones deben tener: pisos lisos y lavables con pendiente a desagües, paredes lisas y lavables (pintura epóxica ideal), techos en buen estado, ventilación adecuada, iluminación suficiente, mallas antiinsectos, separación de áreas sucias/limpias, baños y vestieres para personal, agua potable.', completed: false },
      { id: 79, title: 'Elaboración del Manual de Buenas Prácticas de Manufactura (BPM)', objective: 'Documentar los procedimientos de higiene y operación.', description: 'El manual BPM debe incluir: descripción de la planta, organigrama, calificación del personal, procedimientos de higiene personal, limpieza y desinfección, control de plagas, mantenimiento de equipos, control de agua, manejo de residuos, trazabilidad, y procedimientos específicos de cada proceso productivo.', completed: false },
      { id: 80, title: 'Implementación del Plan de Saneamiento Básico (PSB)', objective: 'Garantizar condiciones sanitarias durante la operación.', description: 'El PSB incluye 4 programas obligatorios: 1) Limpieza y desinfección (POES), 2) Control integrado de plagas, 3) Abastecimiento de agua potable, 4) Manejo de residuos sólidos. Documenta cada programa con procedimientos, frecuencias, responsables y registros.', completed: false },
      { id: 81, title: 'Capacitación del personal en BPM', objective: 'Formar al equipo en higiene y manipulación de alimentos.', description: 'Todo el personal que manipula el producto debe recibir capacitación en BPM: lavado de manos, uso de dotación (cofia, tapabocas, bata, guantes), prohibiciones (comer, fumar, usar joyas), reporte de enfermedades. Documenta con listas de asistencia y certificados.', completed: false },
      { id: 82, title: 'Análisis de peligros y puntos críticos de control (HACCP)', objective: 'Identificar y controlar riesgos de inocuidad en el proceso.', description: 'Aunque no siempre es obligatorio para pequeños productores, es buena práctica: identifica peligros biológicos, químicos y físicos en cada etapa. Define PCC como pasteurización, inoculación, almacenamiento. Establece límites críticos y monitoreo.', completed: false },
      { id: 83, title: 'Elaboración de fichas técnicas del producto', objective: 'Documentar las especificaciones del producto final.', description: 'Crea ficha técnica con: nombre del producto, descripción, ingredientes (100% Pleurotus ostreatus), características físicas y químicas (humedad, pH), vida útil, condiciones de almacenamiento, información nutricional, alérgenos (si aplica).', completed: false },
      { id: 84, title: 'Diseño de etiqueta conforme a normativa', objective: 'Cumplir con los requisitos de etiquetado de alimentos.', description: 'La etiqueta debe incluir: nombre del producto, lista de ingredientes, nombre y dirección del fabricante, registro sanitario (cuando se obtenga), contenido neto, fecha de vencimiento, lote, condiciones de almacenamiento, preparación (si aplica), información nutricional.', completed: false },
      { id: 85, title: 'Análisis microbiológico del producto', objective: 'Demostrar la inocuidad del producto ante el INVIMA.', description: 'Envía muestras a un laboratorio acreditado para análisis: mesófilos aerobios, coliformes totales y fecales, mohos y levaduras, Salmonella, Staphylococcus aureus, E. coli. Guarda los certificados. Estos análisis son requisito para el trámite INVIMA.', completed: false },
      { id: 86, title: 'Radicación del trámite ante INVIMA', objective: 'Iniciar formalmente el proceso de obtención del registro sanitario.', description: 'Reúne toda la documentación: formulario de solicitud, RUT, cámara de comercio, uso de suelo, manual BPM, PSB, fichas técnicas, etiquetas, análisis de laboratorio, planos de la planta, descripción del proceso. Radica vía web en la plataforma del INVIMA y paga los derechos.', completed: false },
      { id: 87, title: 'Preparación para visita de inspección', objective: 'Estar listo para la verificación física del INVIMA.', description: 'El INVIMA realizará una visita a tu planta. Prepara: todo el personal con dotación completa, instalaciones impecables, documentos organizados (carpetas por programa), registros diligenciados (limpieza, temperatura, capacitación), personal capacitado para responder preguntas.', completed: false },
      { id: 88, title: 'Seguimiento al trámite y obtención del registro', objective: 'Completar el proceso y obtener el registro sanitario.', description: 'Haz seguimiento al estado del trámite en la plataforma del INVIMA. Responde oportunamente requerimientos. Una vez aprobado, recibirás el número de registro sanitario que debe aparecer en cada etiqueta. El registro tiene vigencia de 10 años y requiere renovación.', completed: false },
      { id: 89, title: 'Mantenimiento del registro y actualizaciones', objective: 'Cumplir con las obligaciones posteriores a la obtención.', description: 'Una vez obtenido el registro: mantén las BPM, actualiza el manual cuando haya cambios, realiza análisis periódicos, lleva registros al día, informa cambios de fórmula o proceso al INVIMA, renueva el registro antes del vencimiento.', completed: false },
      { id: 90, title: 'Alternativas para pequeños productores', objective: 'Evaluar opciones si el registro INVIMA completo es muy complejo al inicio.', description: 'Si estás empezando y el trámite es muy costoso/complicado, considera: 1) Vender solo en circuitos cortos (mercados campesinos, venta directa) donde los requisitos son menores, 2) Aliarte con un productor ya registrado, 3) Tramitar primero el concepto sanitario (más sencillo), 4) Asesorarte con la Secretaría de Salud.', completed: false },
    ],
  },
];
